version: '3.4'

services:
  api:
    image: ghcr.io/subanov/translation-office/api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
  db:
    extends:
      file: to-postgres.yml
      service: to-postgres